version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: eventsphere-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: eventsphere
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend/EventSphere
    container_name: eventsphere-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventsphere?serverTimezone=America/Sao_Paulo
      JAVA_OPTS: -Duser.timezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpass
      JWT_SECRET: your_jwt_secret
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/EventSphere/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: eventsphere-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: